import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { auth } from "@/src/auth";
import SignOutButton from "@/src/components/auth/SignOutButton";
import Navbar from "../components/Navbar";
import "./globals.css";

/** Stesse variabili CSS di globals.css; Geist non è disponibile in next/font su Next 14. */
const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <p className="bg-purple-700 text-white w-full text-center py-2">
          Sono del layout root
        </p>
        <Navbar actions={session?.user ? <SignOutButton /> : null} />
          {children}
      </body>
    </html>
  );
}
